# Hash = ""
Listen_port = 5000
Command_port = 5001
DDTime = 50

serial {
  dev = "/dev/ttyS0"
  baud = "115200"
  data = "8"
  stop = "1"
  flow = "off"
  parity = "none"

  id = 0
  device {
    addr = 0
    model = "ldu781"
	  datatype = "raw"
  }
}

#SZ, ST, RT
command {
  cmd ldu681 {
	set_zero = "SZ\r"
	set_tare = "ST\r"
	reset_tare = "RT\r"
  }
  cmd ldu781 {
	set_zero = "SZ\r"
	set_tare = "ST\r"
	reset_tare = "RT\r"
  }
  cmd HBraw {
	set_zero = "SZ\r"
	set_tare = "ST\r"
	reset_tare = "RT\r"
  }
}

#S+011005'\r'
Length = 9

Weight {
	Position = 1
	Length = 7
}

