# Hash = ""
Listen_port = 5000
Command_port = 5001
#ip = "192.168.0.049"

serial {
  dev = "/dev/ttyS3"
  baud = "115200"
  data = "8"
  stop = "1"
  flow = "off"
  parity = "none"

  id = 1
  device {
    addr = 0
    model = "ldu781"
  }
}

#SZ, ST, RT
command {
  cmd ldu682 {
	set_zero = "SZ\r"
	set_tare = "ST\r"
	reset_tare = "RT\r"
  }
  cmd ldu781 {
	set_zero = "SZ\r"
	set_tare = "ST\r"
	reset_tare = "RT\r"
  }
}

#W+00100+011005109'\r'
Length = 18

Weight {
	Position = 2
	Length = 6
}

Status {
	Position = 0
	Length = 2
	Stable = "ST"
	Unstable = "US"
	OverLoad = "OL"
	UnderLoad = ""
}

Gross {
	Position = 7
	Length = 5
	Net = "NT"
	Gross = "GS"
}

Unit {
	Position = 14
	Length = 2
	Kg = "kg"
	g = " g"
}

