# Hash = ""
Listen_port = 5000

serial {
  dev = "/dev/ttyS2"
#  dev = "/dev/pts/2"
  baud = "115200"
  data = "8"
  stop = "1"
  flow = "off"
  parity = "none"

#	cmd_get = "GW\r"
#	cmd_cont_get = "SW\r"
#	cmd_zero=""
#	cmd_tara = ""

  device {
    id = 0
    addr = 0
    model = "ldu681"
  }
}
#W+000100+0011005109

Length = 18

Weight {
	Position = 2
	Length = 6
}

Status {
	Position = 0
	Length = 2
	Stable = "ST"
	Unstable = "US"
	OverLoad = "OL"
	UnderLoad = ""
}

Gross {
	Position = 7
	Length = 6
	Net = "NT"
	Gross = "GS"
}

Unit {
	Position = 14
	Length = 2
	Kg = "kg"
	g = " g"
}

