# Hash = ""
Listen_port = 5000
Command_port = 5001
ip = "192.168.0.201"

serial {
  dev = "/dev/ttyS1"
  baud = "115200"
  data = "8"
  stop = "1"
  flow = "off"
  parity = "none"

  id = 0
  device {
    addr = 0
    model = "dis2"
  }
}

serial {
  dev = "/dev/ttyS2"
  baud = "115200"
  data = "8"
  stop = "1"
  flow = "off"
  parity = "none"

  id = 1
  device {
    addr = 0
    model = "dis2"
  }
}

serial {
  dev = "/dev/ttyS3"
  baud = "115200"
  data = "8"
  stop = "1"
  flow = "off"
  parity = "none"

  id = 2
  device {
    addr = 0
    model = "dis2"
  }
}

#SZ, ST, RT
command {
  cmd ldu681 {
	set_zero = "SZ\r"
	set_tare = "ST\r"
	reset_tare = "RT\r"
  }
  cmd dis2 {
	set_zero = "Z"
	set_tare = "T"
  }
}

Length = 16

Weight {
	Position = 0
	Length = 8
}

Status {
	Position = 0
	Length = 2
	Stable = "ST"
	Unstable = "US"
	OverLoad = "OL"
	UnderLoad = ""
}

Gross {
	Position = 7
	Length = 5
	Net = "0"
	Gross = "0"
}

Unit {
	Position = 14
	Length = 2
	Kg = "kg"
	g = " g"
}

