static {
	chan=0		// номер весового канала
	weight_intervals={0,1000,10000,20000}	// интервалы веса
	weight_steps={2,5,15,10}			// шаги прироста веса по интервалам
	time_step=30	// промежуток времени, через который будет формироваться следующий весовой пакет
}

