/*
 * This is a sample devdrvd config
 *
 */

listen-on=0.0.0.0
port=6000
cport=6001

// real com port scale
scale 0 {
    ip=127.0.0.1
    port=5000
    cport=5001
}

/*
// gpio client configuration
gpio 0 {
    ip=127.0.0.1
    port=1500
    cport=7001

    device {
        gpio-in=0:7
        gpio-out=8:11
    }
}
*/